<html>
<head>
<style>
@page {
	size: 8.5in 11in;
	sheet-size: Letter;
	margin: 7%;
	margin-header: 5mm; 
	margin-footer: 5mm;
	odd-footer-name: html_rxFooter;
	even-footer-name: html_rxFooter;
}

body {
	font-family: Arial, sans-serif;
	font-size: 11;
}

h2 {
	text-align: center;
}

p {
	text-align: center;
}

div.outline {
	border: 1;
	border-style: solid;
}

p.borders {
	border: 1;
	border-style: solid;
}

table.top {
	width: 700;
}

table.order {
	width: 700;
}

th {
	background-color: gray;
	color: #FFFFFF;
}
</style>
</head>
<body>
<div id="clinicDetails">
	<h2 style="text-align:center;">
		<?php echo $practiceName;?>
	</h2>
	<p style="text-align:center;">
		<?php echo $practiceInfo;?>
		<?php echo auto_link(prep_url($website));?>
	</p>
</div>
<p><b><?php echo $title;?></b></p>
<table style="width:700" cellspacing="10">
	<tr>
		<th style="width:350">PATIENT INFORMATION</th>
		<th style="width:350">ENCOUNTER INFORMATION</th>
	</tr>
	<tr>
		<td>
			<h4><?php echo $patientInfo->lastname. ', ' . $patientInfo->firstname;?></h4>
			Date of Birth: <?php echo $dob;?><br>
			Current Age: <?php echo $age;?><br>
			Age at Date of Service: <?php echo $age1;?><br>
			Gender: <?php echo $gender;?><br>
		</td>
		<td>
			<h4>Encounter <?php echo $eid;?></h4>
			Date of Service: <?php echo $encounter_DOS;?><br>
			Provider: <?php echo $encounter_provider;?><br>
			Status: <?php echo $status;?><br>
		</td>
	</tr>
</table><br>
<hr />

<h4>Chief Complaint:</h4>
<p class="view"><?php echo $encounter_cc;?></p>
<?php echo $hpi;?>
<?php echo $ros;?>
<?php echo $oh;?>
<?php echo $vitals;?>
<?php echo $pe;?>
<?php echo $labs;?>
<?php echo $procedure;?>
<?php echo $assessment;?>
<?php echo $orders;?>
<?php echo $rx;?>
<?php echo $plan;?>
<br />	
<hr />
<?php echo $billing;?>

<htmlpagefooter name="rxFooter" style="display:none">
<p>The information on this page is CONFIDENTIAL.  Any release of this information requires the expressed written authorization of the patient listed above.  For questions regarding this document, please contact the practice.</p>
<p>This document was generated by NOSH EMR.</p>
</htmlpagefooter>
</body>
</html>