<html>
<head>
<style>
@page {
	size: 8.5in 11in;
	sheet-size: Letter;
	margin: 92px 95px 92px 95px;
	margin-header: 0mm; 
	margin-footer: 5mm;
	odd-footer-name: html_rxFooter;
	even-footer-name: html_rxFooter;
}

body {
	font-family: Arial, sans-serif;
	font-size: 13;
}

p {
	text-align: center;
}
</style>
</head>
<body>
<?php echo $practiceName;?><br><?php echo $practiceInfo1;?><br><?php echo $practiceInfo2;?><br><?php echo $practiceInfo3;?>
<br><br><br><br><br><br>
<?php echo $patientInfo1;?><br><?php echo $patientInfo2;?><br><?php echo $patientInfo3;?>
<div align="right">
	<br><br><br><?php echo $date;?>
</div>
Dear <?php echo $firstname;?>,<br><br><?php echo $body;?><br><br>Sincerely,<br><br><br><br><?php echo $displayname;?>
<htmlpagefooter name="rxFooter" style="display:none">
<p>The information on this page is CONFIDENTIAL.  Any release of this information requires the expressed written authorization of the patient listed above.  For questions regarding this document, please contact the practice.</p>
<p>This document was generated by NOSH EMR.</p>
</htmlpagefooter>
</body>
</html>
