#!/bin/sh

# Source debconf library
. /usr/share/debconf/confmodule
db_version 2.0
db_capb_backup
if ! [ -f /var/www/nosh/system/application/config/database.php ]; then
	STATE=1
	while [ "$STATE" != 0 -a "$STATE" != 5 ]; do
		case "$STATE" in
		1)
			db_input critical noshemr/documents_directory || true
		;;
		2)
			db_input critical noshemr/mysql_database || true
		;;
		3)
			db_input critical noshemr/mysql_username || true
		;;
		4)
			db_input critical noshemr/mysql_password || true
		;;
		esac
		if db_go; then
			STATE=$(($STATE + 1))
		else
			STATE=$(($STATE - 1))
		fi
	done
fi
