#!/bin/sh

set -e
groupadd ftpshared
usermod -a -G ftpshared www-data
if [ ! -d /srv ]; then
	mkdir /srv
fi
mkdir /srv/ftp
mkdir /srv/ftp/shared
chown root:ftpshared /srv/ftp/shared
chmod 775 /srv/ftp/shared
log_only "FTP Shared folder created."
cp /etc/ssh/sshd_config /etc/ssh/sshd_config.bak
log_only "Backup of SSH config file created."
sed -i '/Subsystem/s/^/#/' /etc/ssh/sshd_config
echo 'Subsystem sftp internal-sftp' >> /etc/ssh/sshd_config
echo 'Match group ftpshared' >> /etc/ssh/sshd_config
echo 'ChrootDirectory /srv/ftp/shared' >> /etc/ssh/sshd_config
echo 'X11Forwarding no' >> /etc/ssh/sshd_config
echo 'AllowTCPForwarding no' >> /etc/init/mcservice.conf
echo 'ForceCommand internal-sftp' >> /etc/init/mcservice.conf
log_only "SSH config file updated."
service ssh restart
log_only "SSH service restarted."
